// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Mon Jan 08 00:44:13 2024

ALU_SELECT ALU_SELECT_inst
(
	.IR(IR_sig) ,	// input [7:0] IR_sig
	.op(op_sig) ,	// input [2:0] op_sig
	.op_mux(op_mux_sig) ,	// input  op_mux_sig
	.operand(operand_sig) 	// output [2:0] operand_sig
);

